import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "./(components)/Navigation";

const ptSans = PT_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--pt-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptSans.variable} antialiased`}>
        <header>
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  );
}
